# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.pardaillan-roquefeuil.fr/
title: Château de Pardaillan
email: thierry.de-roquefeuil@wanadoo.fr
description: > # "Le Château de Pardaillan à Lugon et l'Ile du Carney, Grand Vin de Bordeaux et Gîte."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: 
  - title: github
    url: 
  - title: linkedin
    url: 
